import { Bot, Cookie, Database, FileText, Scale, ShieldCheck } from 'lucide-react';
import { Link } from 'react-router';
import { LegalList, LegalNote, LegalSection, PublicLegalLayout } from '../components/PublicLegalLayout';
import { usePageSeo } from '../utils/seo';

const legalLinks = [
  { to: '/privacy', title: 'Privacy Policy', text: 'Collection, use, sharing, retention, safeguards and privacy rights.', icon: ShieldCheck },
  { to: '/terms', title: 'Terms of Service', text: 'Subscription, acceptable use, customer data, AI and liability terms.', icon: Scale },
  { to: '/cookies', title: 'Cookie Policy', text: 'Essential cookies, local storage and the controls available to users.', icon: Cookie },
  { to: '/ai-transparency', title: 'AI & Data Transparency', text: 'How AI features work, what is sent and where human review remains required.', icon: Bot },
  { to: '/subprocessors', title: 'Subprocessors', text: 'Core providers used to host, secure, bill and power the service.', icon: Database },
];

export function LegalCenter() {
  usePageSeo({ title: 'Legal & Trust Centre | ZestIQ Canada', description: 'ZestIQ privacy, terms, cookie, AI transparency and service-provider information for Canadian restaurant operators.', path: '/legal' });
  return <PublicLegalLayout eyebrow="Trust centre" title="Clear terms. Responsible data use." description="The policies and operational commitments behind the ZestIQ restaurant platform." lastUpdated="August 20, 2026"><section className="grid gap-4 sm:grid-cols-2">{legalLinks.map(({ to, title, text, icon: Icon }) => <Link key={to} to={to} className="group rounded-3xl border border-black/10 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><Icon className="h-7 w-7 text-[#B58B00]" /><h2 className="mt-5 text-xl font-black group-hover:underline">{title}</h2><p className="mt-2 text-sm leading-6 text-black/55">{text}</p><span className="mt-5 inline-block text-sm font-black">Read policy →</span></Link>)}</section><LegalNote>These documents support product transparency and contract discussions. ZestIQ customers with specific procurement, privacy or data-residency requirements should contact us before rollout.</LegalNote></PublicLegalLayout>;
}

export function CookiePolicy() {
  usePageSeo({ title: 'Cookie Policy | ZestIQ Canada', description: 'Learn about the essential cookies and browser storage used by the ZestIQ website and restaurant operations platform.', path: '/cookies' });
  return <PublicLegalLayout eyebrow="Browser technology" title="Cookie Policy" description="A plain-language explanation of the cookies and local browser storage ZestIQ currently uses." lastUpdated="August 20, 2026"><LegalSection title="1. What we use"><p>ZestIQ uses browser storage and a limited number of essential cookies to keep users signed in, remember interface preferences, scope locally cached data to the correct company and location, and protect normal application operation.</p></LegalSection><LegalSection title="2. Essential technologies"><LegalList><li><strong>Authentication and session storage:</strong> maintains an authorized session and helps route requests to the correct account.</li><li><strong>Preference storage:</strong> remembers interface choices such as sidebar state and active location.</li><li><strong>Application cache:</strong> temporarily preserves scoped operational data for performance and continuity.</li><li><strong>Security and infrastructure:</strong> hosting and payment providers may use necessary cookies to prevent abuse and complete secure account or billing flows.</li></LegalList></LegalSection><LegalSection title="3. No advertising cookies"><p>ZestIQ does not currently use third-party advertising cookies, cross-site behavioural advertising or sell browser activity. If analytics or advertising technology is added later, this policy and any required consent controls will be updated before use.</p></LegalSection><LegalSection title="4. Your controls"><p>You can delete or block cookies and site storage in your browser settings. Blocking essential storage may sign you out, reset preferences or prevent parts of the service from working. Where optional technology is introduced, ZestIQ will provide choices required by applicable law.</p></LegalSection><LegalSection title="5. Contact"><p>Questions can be sent to <a href="mailto:demo@zestiq.ca?subject=ZestIQ%20cookie%20question" className="font-bold underline underline-offset-4">demo@zestiq.ca</a>.</p></LegalSection></PublicLegalLayout>;
}

export function AITransparency() {
  usePageSeo({ title: 'AI & Data Transparency | ZestIQ', description: 'How ZestIQ uses AI for restaurant invoice scanning, recipe matching, ordering, forecasts and in-app assistance.', path: '/ai-transparency' });
  return <PublicLegalLayout eyebrow="Responsible AI" title="AI & Data Transparency" description="What ZestIQ AI does, what data supports it and which decisions stay with restaurant teams." lastUpdated="August 20, 2026"><LegalNote>AI assists the operator; it does not become the operator. Source records, permissions and human approval remain authoritative.</LegalNote><LegalSection title="1. Where AI is used"><LegalList><li>Reading invoice PDFs and photos and extracting supplier, invoice number, lines, units and prices.</li><li>Transcribing handwritten recipe cards and proposing inventory matches.</li><li>Explaining cost, inventory and operational signals through in-app chat.</li><li>Supporting forecasts and suggested orders using authorized company data.</li></LegalList></LegalSection><LegalSection title="2. Data sent for a request"><p>Only content relevant to the feature may be sent, such as a prompt, uploaded document, image, extracted text and the minimum authorized inventory or restaurant context needed to respond. Customer data is not mixed into another customer’s workspace.</p></LegalSection><LegalSection title="3. Provider and retention"><p>ZestIQ currently uses the OpenAI API. OpenAI states that API data is not used to train its models unless the API customer opts in. Default abuse-monitoring logs may be retained for up to 30 days, subject to OpenAI’s current controls and legal requirements.</p></LegalSection><LegalSection title="4. Human review and limitations"><p>AI can misunderstand handwriting, units, supplier names, pack sizes and context. Users must confirm extracted fields and suggested matches before operational records change. AI output is not accounting, legal, employment, food-safety or financial advice and is not used for solely automated decisions with legal or similarly significant effects about people.</p></LegalSection><LegalSection title="5. Improving responsible use"><p>We may evaluate feature performance using diagnostic and feedback data in accordance with the Privacy Policy. Customers should avoid entering unnecessary personal or sensitive information into prompts or uploaded documents.</p></LegalSection></PublicLegalLayout>;
}

export function Subprocessors() {
  usePageSeo({ title: 'Subprocessors | ZestIQ', description: 'Core technology providers that help ZestIQ host, secure, bill and deliver AI-powered restaurant operations software.', path: '/subprocessors' });
  const providers = [['Vercel', 'Application hosting, delivery and server functions'], ['Supabase', 'Authentication and database infrastructure'], ['OpenAI', 'AI inference for enabled scanning, matching and chat features'], ['Stripe', 'Subscription billing and payment processing']];
  return <PublicLegalLayout eyebrow="Service providers" title="Subprocessors" description="Core providers that may process customer or account information to help ZestIQ deliver the service." lastUpdated="August 20, 2026"><LegalSection title="Core providers"><div className="overflow-hidden rounded-2xl border border-black/10">{providers.map(([name, purpose]) => <div key={name} className="grid gap-1 border-b border-black/10 p-4 last:border-b-0 sm:grid-cols-[150px_1fr]"><p className="font-black text-[#0B1220]">{name}</p><p>{purpose}</p></div>)}</div><p>Providers may process information in Canada, the United States or other jurisdictions where they operate. Customer-selected POS, scheduling or other integrations are engaged under the customer’s direction and may have their own subprocessors.</p></LegalSection><LegalSection title="Changes and questions"><p>We may update this list as providers change. Where a contract requires advance notice of a material new subprocessor, that notice will be provided under the contract. Questions can be sent to <a href="mailto:demo@zestiq.ca?subject=ZestIQ%20subprocessor%20question" className="font-bold underline underline-offset-4">demo@zestiq.ca</a>.</p></LegalSection></PublicLegalLayout>;
}
