import { LegalList, LegalNote, LegalSection, PublicLegalLayout } from '../components/PublicLegalLayout';
import { usePageSeo } from '../utils/seo';

export function Privacy() {
  usePageSeo({ title: 'Privacy Policy | ZestIQ Canada', description: 'How ZestIQ collects, uses, shares, protects and retains personal information for its Canadian restaurant operations platform.', path: '/privacy' });
  return <PublicLegalLayout eyebrow="Privacy & data protection" title="Privacy Policy" description="How ZestIQ handles personal information across our website, management platform, employee scheduling experience, integrations and AI features." lastUpdated="August 20, 2026">
    <LegalNote>This policy is a Canadian SaaS privacy baseline reflecting PIPEDA principles and substantially similar provincial laws. Specific rights and obligations may vary by province and customer relationship.</LegalNote>
    <LegalSection title="1. Who we are and when this policy applies"><p>ZestIQ provides restaurant inventory, purchasing, costing, scheduling, reporting and AI-assisted software. “ZestIQ,” “we,” “us” and “our” refer to the operator of zestiq.ca and the ZestIQ services.</p><p>For account, website, billing and demo-request information, ZestIQ generally decides why information is processed. For restaurant employee, supplier, POS and operating data entered by a customer, the customer generally controls the information and ZestIQ processes it to provide the service.</p><p>A company owner or administrator is responsible for appropriate employee and third-party notices, required consent and lawful use of the service.</p></LegalSection>
    <LegalSection title="2. Information we collect"><LegalList><li><strong>Identity and contact:</strong> name, work email, phone number, role, restaurant or company name and demo-request details.</li><li><strong>Account and security:</strong> user ID, role, company and location access, authentication and reset records, sessions, last login and app usage.</li><li><strong>Restaurant operations:</strong> inventory, suppliers, invoices, orders, recipes, menu items, prices, sales summaries, waste, locations and forecasts.</li><li><strong>Employee scheduling:</strong> name, work contact details, role, hourly rate, schedule, availability, shift requests and optional time-off notes. Customers should not enter medical details unless necessary and lawful.</li><li><strong>Billing:</strong> plan, billing frequency, payment status, dates and limited payment-method details from Stripe. ZestIQ does not receive full card numbers or security codes.</li><li><strong>AI content:</strong> prompts, documents and images, extracted text, suggested matches and AI responses.</li><li><strong>Technical data:</strong> IP address, device and browser information, diagnostic logs, requests and browser storage required to run and secure the service.</li></LegalList></LegalSection>
    <LegalSection title="3. How and why we use information"><p>We collect information from users and company administrators; through files, camera capture and forms; from authorized integrations; and automatically when the service is used.</p><LegalList><li>Provide, secure, support and administer accounts and subscriptions.</li><li>Keep companies and locations logically separated and enforce permissions.</li><li>Run inventory, invoice, recipe, ordering, costing, sales, labour and scheduling workflows.</li><li>Generate AI-assisted extraction, matching, forecasts and explanations.</li><li>Respond to demos, support, privacy requests and security incidents.</li><li>Diagnose errors, understand product usage and improve reliability.</li><li>Meet legal, regulatory, tax, accounting and security obligations.</li></LegalList><p>We limit collection, use and disclosure to appropriate identified purposes. Where consent is required, it may be withdrawn subject to legal or contractual limits and reasonable notice.</p></LegalSection>
    <LegalSection title="4. AI processing and human review"><p>When a user activates an AI feature, relevant prompts, document content and authorized company data may be sent to OpenAI to produce the requested output. OpenAI states that API data is not used to train its models unless the API customer opts in, and that default abuse-monitoring logs may be retained for up to 30 days.</p><p>AI can be incomplete or incorrect. Users remain responsible for reviewing invoice posting, recipe matches, costs, orders, schedules and operational decisions. ZestIQ does not use AI to make solely automated decisions producing legal or similarly significant effects about individuals.</p><p>See our <a href="/ai-transparency" className="font-bold underline underline-offset-4">AI &amp; Data Transparency Notice</a>.</p></LegalSection>
    <LegalSection title="5. When information is shared"><p>We do not sell personal information. We may disclose it to authorized company users; infrastructure, database, AI, payment, email and support providers; customer-selected integrations; professional advisers under confidentiality; transaction parties; and authorities where required or permitted by law.</p><p>Our current core provider list is on the <a href="/subprocessors" className="font-bold underline underline-offset-4">Subprocessors page</a>.</p></LegalSection>
    <LegalSection title="6. Processing outside Canada"><p>Providers may process information in Canada, the United States or other countries where they operate. Information there may be accessible to local courts or authorities. We assess providers and use contractual, access and security measures appropriate to the information. Customers with residency requirements should contact us before enabling an integration or AI feature.</p></LegalSection>
    <LegalSection title="7. Retention, deletion and safeguards"><p>We retain information only as long as reasonably needed to provide the service, resolve disputes, maintain security and satisfy legal, tax and accounting requirements. When no longer required, it is deleted, anonymized or securely disposed of, subject to backups and legal holds.</p><p>We use administrative, technical and physical safeguards appropriate to the sensitivity and volume of information, including role-based access, company and location scoping, monitoring and secure transmission. No internet service can guarantee absolute security.</p><p>We investigate incidents and notify customers, individuals or regulators where required. We keep breach records where the law requires them.</p></LegalSection>
    <LegalSection title="8. Access, correction and choices"><p>Subject to applicable law, an individual may ask to access information under our control, understand its use and disclosure, correct it, withdraw consent or challenge our compliance. We may verify identity first and will respond within the legally required time.</p><p>For information managed by an employer or restaurant customer, contact that organization first. ZestIQ assists the customer as required by contract and law.</p></LegalSection>
    <LegalSection title="9. Marketing, browser storage and children"><p>Commercial electronic messages are sent only with consent or another lawful basis, identify the sender and include an unsubscribe method. Necessary service, billing and security messages may still be sent.</p><p>We use essential browser storage and limited cookies for authentication, preferences and app operation. We do not currently use advertising cookies or behavioural advertising. See our <a href="/cookies" className="font-bold underline underline-offset-4">Cookie Policy</a>.</p><p>ZestIQ is a business service and is not directed to children under 18.</p></LegalSection>
    <LegalSection title="10. Privacy accountability, complaints and changes"><p>ZestIQ’s Privacy Officer is responsible for this program. Send questions, access requests, complaints or incident reports to <a href="mailto:demo@zestiq.ca?subject=ZestIQ%20privacy%20request" className="font-bold underline underline-offset-4">demo@zestiq.ca</a> with “Privacy” in the subject. An individual may also contact the Office of the Privacy Commissioner of Canada or the applicable provincial regulator.</p><p>We may update this policy as the service, providers or law changes. We will post the revised version with a new effective date and give additional notice where required.</p></LegalSection>
  </PublicLegalLayout>;
}
