import { LegalList, LegalNote, LegalSection, PublicLegalLayout } from '../components/PublicLegalLayout';
import { usePageSeo } from '../utils/seo';

export function Terms() {
  usePageSeo({ title: 'Terms of Service | ZestIQ Canada', description: 'Terms governing subscriptions and use of the ZestIQ restaurant inventory, costing, scheduling and AI operations platform.', path: '/terms' });
  return <PublicLegalLayout eyebrow="Subscription agreement" title="Terms of Service" description="The agreement governing zestiq.ca, the ZestIQ management platform, ZestEmployee and related services." lastUpdated="August 20, 2026">
    <LegalNote>These Terms are for business customers. A signed order form or separate agreement controls where it expressly conflicts with these Terms.</LegalNote>
    <LegalSection title="1. Agreement and authority"><p>By creating an account, accepting an order, paying for or using the service, you agree to these Terms for yourself and the company you represent (“Customer”) and confirm you can bind Customer. The service is for authorized business users aged 18 or older.</p></LegalSection>
    <LegalSection title="2. Service and accounts"><p>ZestIQ provides restaurant inventory, invoices, recipes, beverage costing, purchasing, forecasting, labour scheduling, reporting, employee self-service and AI-assisted features. Upcoming, beta, preview or activation-dependent features are not guaranteed until generally available or included in a signed order.</p><LegalList><li>Customer must provide accurate information and keep billing details current.</li><li>Each user must use an individual account and protect credentials.</li><li>Owners and administrators control users, roles, locations and permissions.</li><li>Customer must remove former users promptly and report suspected compromise.</li><li>Users must not attempt to access another company’s data.</li></LegalList></LegalSection>
    <LegalSection title="3. Subscription, pricing and cancellation"><p>ZestIQ Premium is CAD $249.99 per month and includes one location. Each additional location is CAD $100 per month. There is no free trial. Taxes are additional.</p><p>Subscriptions are billed monthly in advance and automatically renew until cancelled. Customer authorizes recurring charges for fees, locations and taxes. We may change pricing on at least 30 days’ notice for a future renewal.</p><p>Customer may cancel before renewal. Cancellation takes effect at the end of the paid billing period. Paid fees are non-refundable except where required by law or agreed in writing. Failed payment may result in retries, feature restriction or suspension after reasonable notice.</p></LegalSection>
    <LegalSection title="4. Customer data and privacy"><p>Customer owns data it submits and grants ZestIQ a limited right to host, copy, transmit, process and display it only to provide, secure and support the service, comply with law and follow Customer instructions.</p><p>Customer is responsible for the legality, accuracy and notices or consents required for employee, supplier, POS, invoice, sales and other data. See the <a href="/privacy" className="font-bold underline underline-offset-4">Privacy Policy</a> and <a href="/subprocessors" className="font-bold underline underline-offset-4">Subprocessors page</a>.</p></LegalSection>
    <LegalSection title="5. AI and operational decisions"><p>AI extraction, matching, chat, forecasts and ordering outputs are probabilistic and may be wrong. Customer must review source records and outputs before posting invoices, changing costs, placing orders, publishing schedules or making financial, employment, food-safety or legal decisions.</p><p>ZestIQ does not provide accounting, tax, employment, legal, food-safety or financial advice. See the <a href="/ai-transparency" className="font-bold underline underline-offset-4">AI &amp; Data Transparency Notice</a>.</p></LegalSection>
    <LegalSection title="6. Labour and employee features"><p>Scheduling, hourly-rate and labour-cost features are planning tools. Customer remains responsible for employment standards, overtime, breaks, payroll, tax, union, accessibility, human-rights and workplace privacy obligations in each jurisdiction.</p></LegalSection>
    <LegalSection title="7. Acceptable use"><LegalList><li>Do not use the service unlawfully or violate privacy, employment or intellectual-property rights.</li><li>Do not upload malware, harmful content or data you are not authorized to process.</li><li>Do not bypass security, authentication, rate limits or company separation.</li><li>Do not reverse engineer, scrape, resell or use the service to build a competing product except where a restriction is prohibited by law.</li><li>Do not represent unreviewed AI output as verified fact.</li></LegalList></LegalSection>
    <LegalSection title="8. Integrations, intellectual property and confidentiality"><p>Customer-selected POS, scheduling, payment or other integrations remain subject to their own terms. ZestIQ is not responsible for third-party availability or acts outside our control.</p><p>ZestIQ owns the service, software, design, documentation and trademarks. During an active subscription, Customer receives a limited, non-exclusive, non-transferable right to use the service internally.</p><p>Each party will protect the other’s non-public business, technical and financial information with reasonable care and use it only for the relationship, subject to standard exclusions and legally compelled disclosure.</p></LegalSection>
    <LegalSection title="9. Availability, suspension and termination"><p>We aim for a reliable service but do not guarantee uninterrupted or error-free operation. Maintenance, internet failures, security events and third-party outages may affect availability. Any service level must be in a signed agreement.</p><p>We may suspend or terminate for material breach, unlawful or unsafe use, non-payment, security threats or legal requirements. Where practical, we will provide notice and a chance to cure. After termination, Customer should request any available export promptly; data may later be deleted subject to legal retention and backups.</p></LegalSection>
    <LegalSection title="10. Disclaimers and liability"><p>To the maximum extent permitted by law, the service is provided “as is” and “as available.” We disclaim implied warranties of merchantability, fitness, non-infringement and guaranteed accuracy or savings, except rights that cannot legally be excluded.</p><p>Neither party is liable for indirect, consequential, special, exemplary or punitive damages or lost profits, revenue, goodwill or data. Except for payment obligations, confidentiality, infringement, fraud, wilful misconduct or liability that cannot be limited, total aggregate liability is limited to subscription fees paid or payable in the six months before the event giving rise to the claim.</p></LegalSection>
    <LegalSection title="11. Indemnity"><p>Customer will defend and indemnify ZestIQ from third-party claims arising from Customer data, unlawful use or material breach of the data, labour or acceptable-use sections, except to the extent caused by ZestIQ.</p></LegalSection>
    <LegalSection title="12. Ontario law, disputes and general terms"><p>These Terms are governed by Ontario law and applicable federal Canadian law. Courts in Toronto, Ontario have exclusive jurisdiction unless a non-waivable law provides otherwise. Before filing a claim, the parties will try in good faith for 30 days to resolve it.</p><p>Neither party is liable for events beyond reasonable control. Customer may not assign these Terms without consent except with a qualifying business sale. If a provision is unenforceable, the rest continues. These Terms and applicable orders are the entire agreement about the service.</p></LegalSection>
    <LegalSection title="13. Changes and notices"><p>Material changes will be posted with a new effective date and, where appropriate, notified through the service or email. Continued use after the effective date means acceptance.</p><p>Send legal notices to <a href="mailto:demo@zestiq.ca?subject=ZestIQ%20legal%20notice" className="font-bold underline underline-offset-4">demo@zestiq.ca</a> with “Legal notice” in the subject. We may notify Customer through the owner email on file.</p></LegalSection>
  </PublicLegalLayout>;
}
